apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "suitecrm7.shortname" . }}-configs
    labels:
        {{ include "suitecrm7.labels" . | nindent 8 }}
        component: deployment
data:
    SUITECRM_DATABASE_COLLATION: {{ .Values.suiteCRM.config.databaseCollation | quote }}
    SUITECRM_DATABASE_DROP_TABLES: {{ .Values.suiteCRM.config.databaseDropTables | quote }}
    SUITECRM_DATABASE_HOST_INSTANCE: {{ .Values.suiteCRM.config.databaseHostInstance | quote }}
    {{ if eq .Values.db.type "internal" }}
    SUITECRM_DATABASE_HOST: "localhost"
    SUITECRM_DATABASE_NAME: {{ .Values.db.internal_db.databaseName | default "suitecrm" | quote }}
    SUITECRM_DATABASE_PASSWORD: {{ .Values.db.internal_db.databasePassword | default "changeme" | quote }}
    SUITECRM_DATABASE_PORT: {{ .Values.db.internal_db.databasePort | default "3306" | quote }}
    SUITECRM_DATABASE_TYPE: "mysql"
    SUITECRM_DATABASE_USE_SSL: false
    SUITECRM_DATABASE_USER_IS_PRIVILEGED: false
    SUITECRM_DATABASE_USER: {{ .Values.db.internal_db.databaseUser | default "suitecrm" | quote }}
    {{ else if eq .Values.db.type "external" }}
    SUITECRM_DATABASE_HOST: {{ .Values.db.external_db.databaseHost | quote }}
    SUITECRM_DATABASE_NAME: {{ .Values.db.external_db.databaseName | quote }}
    SUITECRM_DATABASE_PASSWORD: {{ .Values.db.external_db.databasePassword | quote }}
    SUITECRM_DATABASE_PORT: {{ .Values.db.external_db.databasePort | quote }}
    SUITECRM_DATABASE_TYPE: {{ .Values.db.external_db.databaseType | quote }}
    SUITECRM_DATABASE_USE_SSL: {{ .Values.db.external_db.databaseUseSsl | quote }}
    SUITECRM_DATABASE_USER_IS_PRIVILEGED: {{ .Values.db.external_db.databaseUserIsPrivileged | quote }}
    SUITECRM_DATABASE_USER: {{ .Values.db.external_db.databaseUser | quote }}
    {{ end }}
    {{ if .Values.suiteCRM.adminPassword }}
    SUITECRM_ADMIN_PASSWORD: {{ .Values.suiteCRM.adminPassword | quote }}
    {{ end }}
    {{ if .Values.suiteCRM.adminUsername }}
    SUITECRM_ADMIN_USER: {{ .Values.suiteCRM.adminUsername | quote }}
    {{ end }}
    SUITECRM_CONFIG_LOC: {{ .Values.suiteCRM.config.configLoc | quote }}
    SUITECRM_DEFAULT_CURRENCY_ISO4217: {{ .Values.suiteCRM.config.defaultCurrencyIso4217 | quote }}
    SUITECRM_DEFAULT_CURRENCY_NAME: {{ .Values.suiteCRM.config.defaultCurrencyName | quote }}
    SUITECRM_DEFAULT_CURRENCY_SIGNIFICANT_DIGITS: {{ .Values.suiteCRM.config.defaultCurrencySignificantDigits | quote }}
    SUITECRM_DEFAULT_CURRENCY_SYMBOL: {{ .Values.suiteCRM.config.defaultCurrencySymbol | quote }}
    SUITECRM_DEFAULT_DATE_FORMAT: {{ .Values.suiteCRM.config.defaultDateFormat | quote }}
    SUITECRM_DEFAULT_DECIMAL_SEPERATOR: {{ .Values.suiteCRM.config.defaultDecimalSeperator | quote }}
    SUITECRM_DEFAULT_EXPORT_CHARSET: {{ .Values.suiteCRM.config.defaultExportCharset | quote }}
    SUITECRM_DEFAULT_LANGUAGE: {{ .Values.suiteCRM.config.defaultLanguage | quote }} 
    SUITECRM_DEFAULT_LOCALE_NAME_FORMAT: {{ .Values.suiteCRM.config.defaultLocaleNameFormat | quote }}
    SUITECRM_DEFAULT_NUMBER_GROUPING_SEPARATOR: {{ .Values.suiteCRM.config.defaultNumberGroupingSeparator | quote }}
    SUITECRM_DEFAULT_TIME_FORMAT: {{ .Values.suiteCRM.config.defaultTimeFormat | quote }}
    SUITECRM_EXPORT_DELIMITER: {{ .Values.suiteCRM.config.exportDelimiter | quote }}
    SUITECRM_HOSTNAME: {{ .Values.suiteCRM.config.hostname | quote }}
    SUITECRM_INSTALL_DIR: {{ .Values.suiteCRM.config.installDir | quote }}
    SUITECRM_SETUP_CREATE_DATABASE: {{ .Values.suiteCRM.config.setupCreateDatabase | quote }}
    SUITECRM_SETUP_DEMO_DATA: {{ .Values.suiteCRM.config.setupDemoData | quote }}
    SUITECRM_SITE_NAME: {{ .Values.suiteCRM.siteName | quote }}
    SUITECRM_SITE_URL: {{ .Values.suiteCRM.siteUrl | quote }}