kind: Secret
apiVersion: v1
metadata:
  name: {{ include "suitecrm7.shortname" $ }}-credentials
  labels: 
    {{- include "suitecrm7.labels" . | nindent 8 }}
type: Opaque
data:
  {{ if eq .Values.db.type "internal" }}
  - key: database_root_password 
    value: {{ .Values.db.internal_db.mariadbRootPassword | quote }}
  - key: database_name
    value: {{ .Values.db.internal_db.databaseName | quote }}
  - key: database_user
    value: {{ .Values.db.internal_db.databaseUser | quote }}
  - key: database_password
    value: {{ .Values.db.internal_db.databasePassword | quote }}
  - key: mariadb_auto_upgrade
    value: {{ .Values.db.internal_db.mariadbAutoUpgrade | quote }}
  {{- else if eq .Values.db.type "external" -}}
  - key: database_name
    value: {{ .Values.db.external_db.databaseName | quote }}
  - key: database_user
    value: {{ .Values.db.external_db.databaseUser | quote }}
  - key: database_password
    value: {{ .Values.db.external_db.databasePassword | quote }}    
  {{- end }}
  - key: suitecrm_admin_username
    value: {{ .Values.suiteCRM.adminUsername | quote }}
  - key: suitecrm_admin_password
    value: {{ .Values.suiteCRM.adminPassword | quote }}