kind: Secret
apiVersion: v1
metadata:
  name: {{ include "suitecrm7.shortname" $ }}-credentials
  labels: 
    {{- include "suitecrm7.labels" . | nindent 8 }}
type: Opaque
data:
  {{ if eq .Values.db.type "internal" }}
  database_root_password: {{ .Values.db.internal_db.mariadbRootPassword | quote }}
  database_name: {{ .Values.db.internal_db.databaseName | quote }}
  database_user: {{ .Values.db.internal_db.databaseUser | quote }}
  database_password: {{ .Values.db.internal_db.databasePassword | quote }}
  mariadb_auto_upgrade: {{ .Values.db.internal_db.mariadbAutoUpgrade | quote }}
  {{- else if eq .Values.db.type "external" -}}
  database_name: {{ .Values.db.external_db.databaseName | quote }}
  database_user: {{ .Values.db.external_db.databaseUser | quote }}
  database_password: {{ .Values.db.external_db.databasePassword | quote }}    
  {{- end }}
  suitecrm_admin_username: {{ .Values.suiteCRM.adminUsername | quote }}
  suitecrm_admin_password: {{ .Values.suiteCRM.adminPassword | quote }}