kind: Secret
apiVersion: v1
metadata:
  name: {{ include "suitecrm7.shortname" $ }}-credentials
  labels: 
    {{- include "suitecrm7.labels" . | nindent 8 }}
type: Opaque
data:
  {{ if eq .Values.db.type "internal" }}
  {{ if .Values.db.internal_db.mariadbRootPassword }}
  database_root_password: {{ .Values.db.internal_db.mariadbRootPassword | b64enc | quote }}
  {{ end }}
  database_name: {{ .Values.db.internal_db.databaseName | b64enc | quote }}
  database_user: {{ .Values.db.internal_db.databaseUser | b64enc | quote }}
  database_password: {{ .Values.db.internal_db.databasePassword | b64enc | quote }}
  mariadb_auto_upgrade: {{ .Values.db.internal_db.mariadbAutoUpgrade | b64enc | quote }}
  {{- else if eq .Values.db.type "external" -}}
  database_name: {{ .Values.db.external_db.databaseName | b64enc | quote }}
  database_user: {{ .Values.db.external_db.databaseUser | b64enc | quote }}
  database_password: {{ .Values.db.external_db.databasePassword | b64enc | quote }}    
  {{- end }}
  suitecrm_admin_username: {{ .Values.suiteCRM.adminUsername | b64enc | quote }}
  suitecrm_admin_password: {{ .Values.suiteCRM.adminPassword | b64enc | quote }}